from django.db import models

# Create your models here.
class Employee(models.Model):
    fname = models.CharField(max_length=20)
    lname = models.CharField(max_length=20)
    contact = models.CharField(max_length=20)
    gender = models.CharField(max_length=20)
    dob=models.DateField()
    address=models.CharField(max_length=30)
    state=models.CharField(max_length=20)
    bloodGroup=models.CharField(max_length=20)
    managerName=models.CharField(max_length=30,null=True)
    managerId = models.CharField(max_length=20, null=True)
    joinDate=models.DateField(null=True)
    salary=models.IntegerField(null=True, default=0)
    leave=models.IntegerField(null=True, default=0)
    qualification=models.CharField(max_length=30)
    activation_Date = models.DateTimeField(null=True)
    deactivation_Date = models.DateTimeField(null=True)
    account = models.CharField(max_length=20, default="Deactive")
    emailId=models.EmailField()
    password=models.CharField(max_length=20)
    resume = models.FileField(upload_to='documents', null=True)
    about = models.CharField(max_length=40, null=True)
    image =models.ImageField(upload_to='images/', null=True)
    empCode = models.CharField(primary_key=True, editable=False, max_length=10, unique=True,default="None")
