# Generated by Django 5.1.4 on 2024-12-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('bloodGroup', models.CharField(max_length=20)),
                ('managerName', models.CharField(max_length=30, null=True)),
                ('managerId', models.CharField(max_length=20, null=True)),
                ('joinDate', models.DateField(null=True)),
                ('salary', models.IntegerField(default=0, null=True)),
                ('leave', models.IntegerField(default=0, null=True)),
                ('qualification', models.CharField(max_length=30)),
                ('activation_Date', models.DateTimeField(null=True)),
                ('deactivation_Date', models.DateTimeField(null=True)),
                ('account', models.CharField(default='Deactive', max_length=20)),
                ('emailId', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('resume', models.FileField(null=True, upload_to='documents')),
                ('about', models.CharField(max_length=40, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('empCode', models.CharField(default='None', editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
