# Generated by Django 5.1.4 on 2024-12-17 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('emailId', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='E_Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employeeId', models.CharField(max_length=20)),
                ('employeeName', models.CharField(max_length=20, null=True)),
                ('date', models.DateField()),
                ('loginTime', models.DateTimeField()),
                ('logoutTime', models.DateTimeField()),
                ('status', models.CharField(default='Absent', max_length=20)),
                ('absentStatus', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='E_Holidays',
            fields=[
                ('hoildayId', models.AutoField(primary_key=True, serialize=False)),
                ('holidayName', models.CharField(max_length=20)),
                ('hoildayDescription', models.CharField(max_length=30)),
                ('hoildayDate', models.DateField()),
                ('hoildayDay', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='E_Leave',
            fields=[
                ('leaveId', models.AutoField(primary_key=True, serialize=False)),
                ('employeeId', models.CharField(max_length=20)),
                ('employeeName', models.CharField(max_length=20, null=True)),
                ('managerId', models.CharField(max_length=20, null=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('totalDays', models.IntegerField(default=0)),
                ('employeeReason', models.CharField(max_length=40)),
                ('managerReason', models.CharField(max_length=40)),
                ('appliedDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(max_length=10)),
                ('leaveType', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='E_monthSalary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empCode', models.CharField(max_length=20)),
                ('dateCreated', models.DateTimeField(null=True)),
                ('date', models.DateField(null=True)),
                ('month', models.CharField(max_length=20, null=True)),
                ('year', models.IntegerField(null=True)),
                ('totalTime', models.IntegerField()),
                ('finalSalary', models.IntegerField()),
                ('status', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='employeeDailyWork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employeeId', models.CharField(max_length=20)),
                ('employeeName', models.CharField(max_length=20, null=True)),
                ('managerId', models.CharField(max_length=20)),
                ('clientId', models.IntegerField(null=True)),
                ('workDescription', models.CharField(max_length=40, null=True)),
                ('loginTime', models.DateTimeField()),
                ('loginHour', models.TimeField(null=True)),
                ('logoutTime', models.DateTimeField(null=True)),
                ('logoutHour', models.TimeField(null=True)),
                ('date', models.DateField(null=True)),
                ('projectId', models.IntegerField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='M_Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employeeId', models.CharField(max_length=20)),
                ('employeeName', models.CharField(max_length=20, null=True)),
                ('date', models.DateField()),
                ('loginTime', models.DateTimeField()),
                ('logoutTime', models.DateTimeField()),
                ('status', models.CharField(default='Absent', max_length=20)),
                ('absentStatus', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='M_Holidays',
            fields=[
                ('hoildayId', models.AutoField(primary_key=True, serialize=False)),
                ('holidayName', models.CharField(max_length=20)),
                ('hoildayDescription', models.CharField(max_length=30)),
                ('hoildayDate', models.DateField()),
                ('hoildayDay', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='M_Leave',
            fields=[
                ('leaveId', models.AutoField(primary_key=True, serialize=False)),
                ('employeeId', models.CharField(max_length=20)),
                ('employeeName', models.CharField(max_length=20, null=True)),
                ('managerId', models.CharField(max_length=20, null=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('totalDays', models.IntegerField(default=0)),
                ('employeeReason', models.CharField(max_length=40)),
                ('managerReason', models.CharField(max_length=40)),
                ('appliedDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(max_length=10)),
                ('leaveType', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='M_tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employeeId', models.CharField(max_length=20)),
                ('employeeName', models.CharField(max_length=20, null=True)),
                ('managerId', models.CharField(max_length=20)),
                ('clientId', models.IntegerField(null=True)),
                ('projectName', models.CharField(max_length=20, null=True)),
                ('date', models.DateField()),
                ('workDescription', models.CharField(max_length=40, null=True)),
                ('fileUpload', models.FileField(null=True, upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('joinDate', models.DateField(null=True)),
                ('salary', models.IntegerField(default=0, null=True)),
                ('leave', models.IntegerField(default=0, null=True)),
                ('qualification', models.CharField(max_length=30)),
                ('activation_Date', models.DateTimeField(null=True)),
                ('deactivation_Date', models.DateTimeField(null=True)),
                ('account', models.CharField(default='Deactive', max_length=20)),
                ('emailId', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('managerCode', models.CharField(default='None', editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('resume', models.FileField(null=True, upload_to='documents')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='about',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bloodGroup',
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
