# Generated by Django 5.1.4 on 2024-12-24 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0002_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.CharField(max_length=20)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('totalDays', models.IntegerField(default=0)),
                ('employeeReason', models.CharField(max_length=40)),
                ('appliedDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('casual_leave', 'Casual Leave'), ('paid_leave', 'Paid Leave'), ('sick_leave', 'Sick Leave'), ('maternity_leave', 'Maternity Leave'), ('paternity_leave', 'Paternity Leave'), ('unpaid_leave', 'Unpaid Leave'), ('other', 'Other')], default='casual_leave', max_length=20)),
                ('leaveType', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
