# Generated by Django 5.1.4 on 2024-12-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
