# Generated by Django 5.1.4 on 2024-12-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0003_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timeline',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
