# Generated by Django 5.1.4 on 2024-12-21 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0004_profile_image'),
        ('EMS', '0006_alter_attendance_user'),
    ]

    operations = [
    ]
